(function (site) {
  var techBase = "/img/partners/technology/";

  site.content.partners = [];

  site.content.technologyPartners = [
    { name: "Eaton", logo: techBase + "eaton.png" },
    { name: "Huawei", logo: techBase + "huawei.png" },
    { name: "BEG", logo: techBase + "beg.png" },
    { name: "Polycom", logo: techBase + "polycom.png" },
    { name: "Zennio", logo: techBase + "zennio.png" },
    { name: "Gira", logo: techBase + "gira.png" },
    { name: "Interra", logo: techBase + "interra.png" },
    { name: "VOKA", logo: techBase + "voka.png" },
    { name: "Ekinex", logo: techBase + "ekinex.png" },
    { name: "WAGO", logo: techBase + "wago.png" },
    { name: "OBO Bettermann", logo: techBase + "obo-bettermann.png" },
    { name: "Phoenix Contact", logo: techBase + "phoenix-contact.png" },
    { name: "iRidium mobile", logo: techBase + "iridium-mobile.png" },
    { name: "Extron Certified", logo: techBase + "extron-certified.png" },
    { name: "Yealink", logo: techBase + "yealink.png" },
    { name: "Schneider Electric", logo: techBase + "schneider-electric.png" },
    { name: "HDL", logo: techBase + "hdl.png" },
    { name: "ABB", logo: techBase + "abb.png" },
    { name: "Zyxel", logo: techBase + "zyxel.png" },
    { name: "JUNG", logo: techBase + "jung.png" },
    { name: "Yamaha", logo: techBase + "yamaha.png" },
    { name: "Hikvision", logo: techBase + "hikvision.png" },
    { name: "Beckhoff", logo: techBase + "beckhoff.png" },
    { name: "Carrier", logo: techBase + "carrier.png" },
    { name: "Siemens", logo: techBase + "siemens.png" },
    { name: "Legrand", logo: techBase + "legrand.png" },
    { name: "Honeywell", logo: techBase + "honeywell.png" },
    { name: "Helvar", logo: techBase + "helvar.jpg" },
    { name: "Sharp", logo: techBase + "sharp.png" },
    { name: "Dahua", logo: techBase + "dahua.png" },
    { name: "Axis", logo: techBase + "axis.png" },
    { name: "Uniview", logo: techBase + "uniview.png" },
    { name: "Bosch", logo: techBase + "bosch.png" },
    { name: "Hanwha Vision", logo: techBase + "hanwha-vision.png" },
    { name: "Ajax", logo: techBase + "ajax.png" },
    { name: "Cisco", logo: techBase + "cisco.png" },
    { name: "MikroTik", logo: techBase + "mikrotik.png" },
    { name: "TP-Link", logo: techBase + "tp-link.png" },
    { name: "Ubiquiti", logo: techBase + "ubiquiti.png" },
    { name: "ZKTeco", logo: techBase + "zkteco.png" },
    { name: "Akuvox", logo: techBase + "akuvox.png" },
    { name: "2N", logo: techBase + "2n.png" },
    { name: "Paradox", logo: techBase + "paradox.png" },
    { name: "DSC", logo: techBase + "dsc.png" },
    { name: "TOA", logo: techBase + "toa.png" },
    { name: "JBL", logo: techBase + "jbl.png" },
    { name: "Johnson Controls", logo: techBase + "johnson-controls.png" },
    { name: "Crestron", logo: techBase + "crestron.png" },
    { name: "Control4", logo: techBase + "control4.png" },
    { name: "Schrack Seconet", logo: techBase + "schrack-seconet.png" },
    { name: "Grandstream", logo: techBase + "grandstream.png" },
    { name: "Satel", logo: techBase + "satel.png" },
    { name: "Tiandy", logo: techBase + "tiandy.png" },
    { name: "Milesight", logo: techBase + "milesight.png" },
    { name: "ASUS", logo: techBase + "asus.png" },
    { name: "HP", logo: techBase + "hp.png" },
    { name: "Dell", logo: techBase + "dell.png" },
    { name: "Lenovo", logo: techBase + "lenovo.png" },
    { name: "MSI", logo: techBase + "msi.png" },
    { name: "Intel", logo: techBase + "intel.png" },
    { name: "AMD", logo: techBase + "amd.png" },
    { name: "Samsung", logo: techBase + "samsung.png" },
    { name: "Acer", logo: techBase + "acer.png" },
    { name: "LG", logo: techBase + "lg.png" },
    { name: "APC", logo: techBase + "apc.png" },
    { name: "Synology", logo: techBase + "synology.png" },
    { name: "QNAP", logo: techBase + "qnap.png" },
    { name: "Supermicro", logo: techBase + "supermicro.png" }
  ];
})(window.SmartTech);
